### ISSUE TITLE
[프로젝트 구축] log 모듈 추가

### ISSUE THREAD

**Issue by KwonDae** [YAPP-Github/20th-Android-Team-1-FE#14]

**Comment by hoyahozz** [comment]
사고뭉치 @hoyahozz 가 develop 브랜치에 바로 커밋을 해버려서 클로즈...............................................................

**Comment by hoyahozz** [comment]
e5ca46ee70d48120b2e9bbd3d4f9bf993f80fa8a ~ 5e9b70c7409f02b3326d93fee5f550190d98a2ed

**Comment by jihee-dev** [comment]
https://github.com/YAPP-Github/20th-Android-Team-1-FE/commit/e5ca46ee70d48120b2e9bbd3d4f9bf993f80fa8a
https://github.com/YAPP-Github/20th-Android-Team-1-FE/commit/896437c26c70e292f801c2ff5be2f6cc330edab1
https://github.com/YAPP-Github/20th-Android-Team-1-FE/commit/ecbe3ef559a2427454dfd483da85d4a5b95e655a
https://github.com/YAPP-Github/20th-Android-Team-1-FE/commit/5e9b70c7409f02b3326d93fee5f550190d98a2ed
