### ISSUE TITLE
[프로젝트 구축] MVVM vs MVI

### ISSUE THREAD

**Issue by jihee-dev** [YAPP-Github/20th-Android-Team-1-FE#15]
- MVVM과 MVI에 대해 알아 보자!
- 우리 프로젝트에는 어떻게 적용해 볼지 고민해 보자!

**Comment by KwonDae** [comment]
👍

**Comment by KwonDae** [comment]
5/18 까지 부탁드려용 💯

**Comment by jihee-dev** [comment]
- 레퍼런스 레포
https://github.com/wellingtoncabral/android-compose-mvi-navigation
https://github.com/RivuChk/Jetpack-Compose-MVI-Demo

MVVM 기반에 MVI 한 스푼..

**Comment by jihee-dev** [comment]
- MVI (Redux나 다른 라이브러리 사용 X)
  - Event로 사용자의 Intent를 받고, 뷰로 전달될 수 있는 단발성의 이벤트는 SideEffect로 보낸다
- 패키지는 화면당 하나로 정하며 `Screen - Contract - ViewModel`로 구성함
- Contract 내부에 UiState, Event, SideEffect 정의
