### ISSUE TITLE
[프로젝트 구축] 클린 아키텍처 모듈 추가

### ISSUE THREAD

**Issue by KwonDae** [YAPP-Github/20th-Android-Team-1-FE#2]

**Comment by jihee-dev** [comment]
모듈을 어떻게 나누어 놓을지도 의논이 필요할 것 같습니당

**Comment by KwonDae** [comment]
@jihee-dev 
일단
app
    presentation
    data
    domain
으로 가서 프레젠테이션 모듈 더 필요하면 추가하는 방향으로 어때여
